// This file will be auto-generated by `npm run db:types`
// Placeholder types until schema is deployed

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      services: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          type: string
          url: string | null
          hostname: string | null
          port: number | null
          method: string
          headers: Json
          body: string | null
          expected_status: number[]
          keyword: string | null
          json_path: string | null
          expected_value: string | null
          dns_record_type: string | null
          dns_server: string
          docker_host: string | null
          container_name: string | null
          interval_seconds: number
          timeout_seconds: number
          retries: number
          verify_ssl: boolean
          ssl_expiry_alert_days: number
          is_active: boolean
          is_paused: boolean
          tags: string[] | null
          next_check: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          type: string
          url?: string | null
          hostname?: string | null
          port?: number | null
          method?: string
          headers?: Json
          body?: string | null
          expected_status?: number[]
          keyword?: string | null
          json_path?: string | null
          expected_value?: string | null
          dns_record_type?: string | null
          dns_server?: string
          docker_host?: string | null
          container_name?: string | null
          interval_seconds?: number
          timeout_seconds?: number
          retries?: number
          verify_ssl?: boolean
          ssl_expiry_alert_days?: number
          is_active?: boolean
          is_paused?: boolean
          tags?: string[] | null
          next_check?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          type?: string
          url?: string | null
          hostname?: string | null
          port?: number | null
          method?: string
          headers?: Json
          body?: string | null
          expected_status?: number[]
          keyword?: string | null
          json_path?: string | null
          expected_value?: string | null
          dns_record_type?: string | null
          dns_server?: string
          docker_host?: string | null
          container_name?: string | null
          interval_seconds?: number
          timeout_seconds?: number
          retries?: number
          verify_ssl?: boolean
          ssl_expiry_alert_days?: number
          is_active?: boolean
          is_paused?: boolean
          tags?: string[] | null
          next_check?: string
          created_at?: string
          updated_at?: string
        }
      }
      heartbeats: {
        Row: {
          id: string
          service_id: string
          status: string
          response_time_ms: number | null
          status_code: number | null
          message: string | null
          created_at: string
        }
        Insert: {
          id?: string
          service_id: string
          status: string
          response_time_ms?: number | null
          status_code?: number | null
          message?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          service_id?: string
          status?: string
          response_time_ms?: number | null
          status_code?: number | null
          message?: string | null
          created_at?: string
        }
      }
      incidents: {
        Row: {
          id: string
          service_id: string
          started_at: string
          ended_at: string | null
          duration_seconds: number | null
          cause: string | null
          resolution: string | null
          acknowledged: boolean
          acknowledged_by: string | null
          acknowledged_at: string | null
        }
        Insert: {
          id?: string
          service_id: string
          started_at: string
          ended_at?: string | null
          duration_seconds?: number | null
          cause?: string | null
          resolution?: string | null
          acknowledged?: boolean
          acknowledged_by?: string | null
          acknowledged_at?: string | null
        }
        Update: {
          id?: string
          service_id?: string
          started_at?: string
          ended_at?: string | null
          duration_seconds?: number | null
          cause?: string | null
          resolution?: string | null
          acknowledged?: boolean
          acknowledged_by?: string | null
          acknowledged_at?: string | null
        }
      }
      alert_channels: {
        Row: {
          id: string
          user_id: string
          type: string
          name: string
          config: Json
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          name: string
          config: Json
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          name?: string
          config?: Json
          is_active?: boolean
          created_at?: string
        }
      }
      service_alert_channels: {
        Row: {
          service_id: string
          alert_channel_id: string
        }
        Insert: {
          service_id: string
          alert_channel_id: string
        }
        Update: {
          service_id?: string
          alert_channel_id?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
